---
title: "Untitled"
format: html
---


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(viridis)
library(stringr)
```

```{r}
df <- read.csv("gsea_results_AT1.csv")
```

```{r}
top_bottom <- df %>%
  filter(FDR.q.val < 0.05) %>%
  arrange(FDR.q.val) %>%
  group_by(NES > 0) %>%
  slice_head(n = 5) %>%
  ungroup()
```

```{r}
top_bottom$genes_in_set <- as.numeric(gsub("%", "", top_bottom$Gene..))
top_bottom$logFDR <- -log10(top_bottom$FDR.q.val)
```

```{r}
p <- ggplot(top_bottom, aes(x= NES, y = reorder(str_wrap(Term, width = 30), NES), size = genes_in_set, colour = logFDR))+geom_point()+theme_bw()+
    theme(axis.text = element_text(size= 12, colour = "black"),
    text = element_text(size= 12, colour = "black"))+
    scale_colour_viridis(option="G", direction = -1, name = "-log10(FDR)")+ylab(NULL)+
    scale_size_continuous(,
    breaks = c(10, 30),   # choose manually
    limits = c(0, max(top_bottom$genes_in_set)),
    name="% genes in set")+
        geom_vline(xintercept=0, linetype="dashed", colour = "black")
p
ggsave(plot=p, filename="AT1_pathways.png", dpi=300,height=5, width = 8)
```