---
title: "Untitled"
format: html
---


```{python}
import os
import re
import sys
import scanpy as sc
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import anndata as ad
from scipy.stats import median_abs_deviation
import decoupler as dc
```

```{python}
print(sys.executable)
```

```{python}
flex_adata = sc.read_h5ad("flex_adata_clustered.h5ad")
```

```{python}
sc.pl.umap(flex_adata, color = "COL3A1")
```

```{python}
sc.pl.violin(flex_adata, keys = "COL3A1", groupby = "poms_id", layer = "X")
```

### pseudobulk samples
```{python}
pdata = dc.pp.pseudobulk(
    adata=flex_adata,
    sample_col="poms_id",
    groups_col="celltypist_label_foetal_lung_celltypist",
    mode="sum",
    layer="counts",
    skip_checks=True
)
```

### due to soupx usage, the counts are not integers, so i will round here (post-pseudbulking, so the impact is not as strong)
```{python}
pdata.X = np.rint(pdata.X).astype(int)
```

### remove samples with low cell counts
### ~ symbold inverses (so allows me to remove these samples rather than keep)
### also remove middle gestation bin (24-30pcw) to leave two groups, as three can't be compared (also don't have the n numbers anyway)
```{python}
samples = ["POMS_089", "POMS_020", "POMS_039", "POMS_048"]
pdata = pdata[~pdata.obs["poms_id"].isin(samples)].copy()
ages = ["<24pcw", ">30pcw"]
pdata = pdata[pdata.obs["gestation_bin"].isin(ages)].copy()
```

### select celltypes i want to run DEA on
### not only does celltypist predict a lot of celltypes, i only actually want to focus on the AT subsets for now
```{python}
subsets = ["AT1", "AT2"]
pdata = pdata[pdata.obs["celltypist_label_foetal_lung_celltypist"].isin(subsets)].copy()
```

### here we view and then remove samples where they have fewer than 10 cells or 1000 counts
### in this case poms_025 has 0 cells in the AT2 cluster, so no point having them in the comparison as it might break it
```{python}
dc.pl.filter_samples(
    adata=pdata,
    groupby=["gestation_bin", "poms_id", "celltypist_label_foetal_lung_celltypist"],
    min_cells=10,
    min_counts=1000,
    figsize=(5, 8),
)
```

```{python}
dc.pp.filter_samples(pdata, min_cells=10, min_counts=1000)
```

```{python}
at1 = pdata[pdata.obs["celltypist_label_foetal_lung_celltypist"] == "AT1"].copy()
at2 = pdata[pdata.obs["celltypist_label_foetal_lung_celltypist"] == "AT2"].copy()
```

### checking number of samples in each bin
```{python}
at1.obs.groupby("gestation_bin")["poms_id"].nunique()
```

### looped version for running everything quickly
```{python}
from pydeseq2.dds import DeseqDataSet, DefaultInference
from pydeseq2.ds import DeseqStats

celltypes = ["AT1", "AT2"]

inference = DefaultInference(n_cpus=8)

results_dict = {}   # store full results
sig_dict = {}       # store significant genes

for ct in celltypes:
    
    print(f"Running DE for {ct}")
    
    # subset
    adata_ct = pdata[
        pdata.obs["celltypist_label_foetal_lung_celltypist"] == ct
].copy()
    
    # sanity check
    print(adata_ct.obs.groupby("gestation_bin")["poms_id"].nunique())
    
    # DESeq2
    dds = DeseqDataSet(
        adata=adata_ct,
        design_factors=["gestation_bin"],
        refit_cooks=True,
        inference=inference,
    )
    
    dds.deseq2()
    
    stat_res = DeseqStats(
        dds,
        contrast=["gestation_bin", ">30pcw", "<24pcw"],
        inference=inference
    )
    
    stat_res.summary()
    
    # extract results
    res_df = stat_res.results_df.copy()
    
    # store
    results_dict[ct] = res_df
    sig_dict[ct] = res_df[res_df["padj"] < 0.05]
    
    # save to file
    res_df.to_csv(f"DEG_{ct}_all.csv")
    sig_dict[ct].to_csv(f"DEG_{ct}_sig.csv")
```


### plot volcanos or both celltypes with top 10degs labelled
```{python}
fig, axes = plt.subplots(1, 2, figsize=(10, 6), sharex=True, sharey=True)

dc.pl.volcano(
    results_dict["AT1"],
    x="log2FoldChange",
    y="padj",
    top=10,
    thr_stat=1,
    color_pos = "mediumseagreen",
    color_neg = "mediumorchid",
    ax=axes[0]
)
axes[0].set_title("AT1")

dc.pl.volcano(
    results_dict["AT2"],
    x="log2FoldChange",
    y="padj",
    top=10,
    thr_stat=1,
    color_pos = "mediumseagreen",
    color_neg = "mediumorchid",
    ax=axes[1]
)
axes[1].set_title("AT2")

plt.tight_layout()
plt.savefig("AT1_AT2_volcano.png", dpi=300)
plt.show()
```

### plot number of degs in AT1  and AT2
```{python}
filtered_results = {
    ct: df[df["padj"] < 0.05].copy()
    for ct, df in results_dict.items()
}
```

```{python}
deg_number = pd.DataFrame(
    {"number of DEGs" : [ 897, 68],
    "celltype": ["AT1", "AT2"]}
)
plt.figure()
sns.barplot(deg_number, x = "celltype", y= "number of DEGs")
plt.savefig("AT cells DEG number", dpi = 300)
```

### run GSEA using GSEApy
```{python}
import gseapy as gp
```

```{python}
res_df = results_dict["AT2"]

# rank genes (important)
rnk = res_df[["stat"]].dropna()
rnk = rnk.sort_values("stat", ascending=False)

# reset index if needed
rnk.index.name = "gene"
rnk = rnk.reset_index()
```

```{python}
pre_res = gp.prerank(
    rnk=rnk,
    gene_sets="KEGG_2026",
    permutation_num=1000,
    outdir=None,
    seed=42
)
```

```{python}
pre_res.res2d.head(10)
```

```{python}
pre_res.plot(terms=pre_res.res2d.Term.head(5))
```

### filter significant pathways and select top and bottom 5
```{python}
sig = pre_res.res2d[pre_res.res2d["FDR q-val"] < 0.05]

top_pos = (
    sig[sig["NES"] > 0]
    .sort_values("FDR q-val")
    .head(5)
)

top_neg = (
    sig[sig["NES"] < 0]
    .sort_values("FDR q-val")
    .head(5)
)

top_pos["direction"] = ">30pcw"
top_neg["direction"] = "<24pcw"

top_combined = pd.concat([top_pos, top_neg])
```
```{python}
top_terms = top_combined["Term"].unique()
pre_res.plot(terms=top_terms)
```

### saving pathways to csv so that i can load into R and plot in more detail if wanted
```{python}
pre_res.res2d.to_csv("gsea_results_AT2.csv")
```

### plotting a few example genes fromt the pathways for a sense check
```{python}
at2 = flex_adata[
    flex_adata.obs["celltypist_label_foetal_lung_celltypist"] == "AT2"].copy()
```

```{python}
sc.pl.violin(at2, keys=["TNFRSF1A", "IL6R"], groupby="gestation_bin", stripplot=False)
```